---
output: html_document
editor_options: 
  chunk_output_type: console
---

# FAO Data Assembly

```{r, echo = FALSE, results = FALSE, message = FALSE, warning = FALSE}
#| label: set-chunk-options
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)

library(tidyverse)

targets::tar_load(fao_catch)

source("R/functions.R")
```

## Datasets

## Packages

# Methods

## Join FAO Data

[FAO Global Capture Production](https://www.fao.org/fishery/en/collection/capture?lang=en) data was downloaded as .csv files in a zipped folder. The following .csv files were used in this analysis:

- `Capture_Quantity.csv` (catch quantity)
- `CL_FI_COUNTRY_GROUPS.csv` (country information)
- `CL_FI_SPECIES_GROUPS.csv` (species information)

### Remove non-target species

Prior to joining the .csv files, "PISCES", "CRUSTACEA", "MOLLUSCA", and "INVERTEBRATA AQUATICA" were filtered out of the major groups represented in the `CL_FI_SPECIES_GROUPS.csv`. Additionally, [ISSCAAP group](https://www.fao.org/fishery/static/ASFIS/ISSCAAP.pdf) 82 (Corals) was removed. These species were assumed not to be the target species of the fishing gear types ("fishing", "squid_jigger", "drifting_longlines", "pole_and_line", "other_fishing", "trollers", "fixed_gear", "pots_and_traps", "set_longlines", "set_gillnets", "trawlers", "dredge_fishing", "seiners", "purse_seines", "tuna_purse_seines", "other_purse_seines", "other_seines", and "driftnets") represented in the broadcasting emissions dataset. This, however, does have implications for the non-broadcasting dataset (**see...**).

ISSCAAP groups 41 and 51, representing freshwater crustaceans and freshwater molluscs respectively, as well as the species "River eels", were filtered out because any emissions associated with freshwater collection are eliminated during the intersection of the FAO regions shapefile and the emissions grid. Therefore, it is assumed that none of the resulting emissions can be attributed to fishing for freshwater species.

### Add species information

The analysis is conducted with species distinguished by a unique numeric code in the `identifier` column, and then additional species information is joined back to the final table. Species information was obtained from a modified version of the `data-keys/master_species_key.csv` created by Danielle Ferraro and Gordon Blasco and provided by emLab. Some species in the resulting FAO dataset were not represented in the master_species_key.csv, so the missing species were added from the `FAO CL_FI_SPECIES_GROUPS.csv`. 
