---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Results {#sec-results}

```{r, echo = FALSE, results = FALSE, message = FALSE, warning = FALSE}
#| label: set-chunk-options
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)

library(tidyverse)

targets::tar_load(full_emissions_fao_species)
targets::tar_load(full_emissions_sau_species)
targets::tar_load(emissions_partitioned_grouped)

#source("R/functions.R")
```

## Overall Comparisons

```{r}
#| code-summary: Overall
# -------- Total emissions comparison --------
# Make sure total emissions match
total_co2 <- sum(emissions_partitioned_grouped$emissions_co2_mt, na.rm = TRUE)
total_co2_fao <- sum(full_emissions_fao_species$total_co2_mt, na.rm = TRUE)
total_co2_sau <- sum(full_emissions_sau_species$total_co2_mt, na.rm = TRUE)

if (total_co2_fao != total_co2_sau) {
  warning("Total emissions in FAO do not match total emissions in SAU.")
}

# -------- Total catch comparison --------
# Filter for years with FAO/SAU overlap (2016-2019)
full_emissions_fao_filtered <- full_emissions_fao_species %>%
  filter(year <= 2019)

full_emissions_sau_filtered <- full_emissions_sau_species %>%
  filter(year <= 2019)

# Compare total catch to determine underreporting
fao_total_catch <- sum(full_emissions_fao_filtered$country_total_tons_by_species, na.rm = TRUE)
sau_total_catch <- sum(full_emissions_sau_filtered$country_total_tons_by_species, na.rm = TRUE)

# -------- Compare Emissions/Unit Catch --------
fao_total_emissions_catch <- total_co2_fao/fao_total_catch
sau_total_emissions_catch <- total_co2_sau/sau_total_catch

print(paste0("FAO emissions-per-unit-catch: ", round(fao_total_emissions_catch, 2), "."))
print(paste0("SAU emissions-per-unit-catch: ", round(sau_total_emissions_catch, 2), "."))
```

```{r}
#| fig-height: 10
fao_species <- full_emissions_fao_species %>%
  rename(fao_catch_tons = country_total_tons_by_species,
         fao_total_co2_mt = total_co2_mt,
        fao_total_ch4_mt = total_ch4_mt,
         fao_total_n2o_mt = total_n2o_mt,
         fao_total_nox_mt = total_nox_mt,
        fao_total_sox_mt = total_sox_mt,
        fao_total_co_mt = total_co_mt,
        fao_total_vocs_mt = total_vocs_mt,
        fao_total_pm2_5_mt = total_pm2_5_mt,
        fao_total_pm10_mt = total_pm10_mt)

sau_species <- full_emissions_sau_species %>%
  rename(sau_catch_tons = country_total_tons_by_species,
         sau_total_co2_mt = total_co2_mt,
        sau_total_ch4_mt = total_ch4_mt,
         sau_total_n2o_mt = total_n2o_mt,
         sau_total_nox_mt = total_nox_mt,
        sau_total_sox_mt = total_sox_mt,
        sau_total_co_mt = total_co_mt,
        sau_total_vocs_mt = total_vocs_mt,
        sau_total_pm2_5_mt = total_pm2_5_mt,
        sau_total_pm10_mt = total_pm10_mt)

isscaap_comparison <- inner_join(fao_species, sau_species, by = c("zone", "year", "flag", "scientific_name" = "species"))

comp <- isscaap_comparison %>%
  ungroup() %>%
  group_by(isscaap_group, isscaap) %>%
  summarise(fao_co2_emissions = sum(fao_total_co2_mt, na.rm = TRUE),
            fao_catch = sum(fao_catch_tons, na.rm = TRUE),
            sau_co2_emissions = sum(sau_total_co2_mt, na.rm = TRUE),
            sau_catch = sum(sau_catch_tons, na.rm = TRUE)) %>%
  mutate(fao_emissions_unit_catch = fao_co2_emissions/fao_catch,
            sau_emissions_unit_catch = sau_co2_emissions/sau_catch) %>%
  select(isscaap_group, isscaap, fao_emissions_unit_catch, sau_emissions_unit_catch) %>%
  pivot_longer(cols = 3:4, names_to = "entity", values_to = "emissions_unit_catch")

ggplot(comp, aes(reorder(isscaap_group, emissions_unit_catch), emissions_unit_catch, fill = entity)) +
  geom_bar(stat = "identity", position = "dodge") +
   scale_fill_manual(labels = c("FAO", "SAU"), values = c("cornflowerblue", "firebrick")) +
  coord_flip() +
  labs(y = "Emissions/Unit Catch",
       x = "ISSCAAP Group",
       fill = "Reporting\nAgency") +
  theme_minimal()
```

## Visualizations

### Trends in emissions-per-unit-catch by ISSCAAP species group

```{r}
#| code-summary: ISSCAAP Time
#| fig-height: 10
full_emissions_fao_species %>%
  filter(year<=2022) %>%
  filter(!isscaap_group %in% c("no_fao_species_catch_data", "unknown_species")) %>%
  group_by(isscaap_group, isscaap, year) %>%
  summarise(total_emissions_co2 = sum(total_co2_mt, na.rm = TRUE),
            total_catch = sum(country_total_tons_by_species, na.rm = TRUE)) %>%
  mutate(emissions_unit_catch = total_emissions_co2/total_catch) %>%
  ggplot(aes(year, emissions_unit_catch, group = isscaap_group)) +
  geom_line() +
  scale_x_continuous(breaks = seq(2016, 2022, by = 3)) +
  facet_wrap(~isscaap_group, labeller = label_wrap_gen(width = 20), scales = "free_y") +
  labs(x = "",
       y = "Emissions CO2 per Unit Catch") +
  theme_minimal()
```

#### Trends in emissions-per-unit-catch by FAO region

```{r}
#| code-summary: Region Emissions-Catch
# Facet by region
full_emissions_fao_species %>%
  filter(year <= 2022) %>%
  group_by(zone, year) %>%
  summarise(total_emissions_co2 = sum(total_co2_mt, na.rm = TRUE),
            total_catch = sum(country_total_tons_by_species, na.rm = TRUE)) %>%
  mutate(emissions_unit_catch = total_emissions_co2/total_catch) %>%
  ggplot(aes(year, emissions_unit_catch, group = as.factor(zone))) +
  geom_line() +
  scale_x_continuous(breaks = seq(2016, 2024, by = 4)) +
  #scale_y_continuous(labels = scales::comma) +
  facet_wrap(~zone, scales = "free_y") +
  labs(x = "",
       y = "Emissions CO2 per Unit Catch",
       title = "Trends in Global Emissions per Unit Catch by FAO Region") +
  theme_minimal()

full_emissions_fao_species %>%
  filter(year <= 2022) %>%
  group_by(zone, year) %>%
  summarise(total_emissions_co2 = sum(total_co2_mt, na.rm = TRUE),
            total_catch = sum(country_total_tons_by_species, na.rm = TRUE)) %>%
  mutate(emissions_unit_catch = total_emissions_co2/total_catch) %>%
  filter(!zone == 18) %>%
  ggplot(aes(year, emissions_unit_catch, group = as.factor(zone), color = as.factor(zone))) +
  geom_line() +
  scale_x_continuous(breaks = seq(2016, 2024, by = 4)) +
  labs(x = "",
       y = "Emissions CO2 per Unit Catch",
       title = "Trends in Global Emissions per Unit Catch by FAO Region",
       color = "Zone") +
  gghighlight::gghighlight(as.factor(zone) %in% c(58, 88)) +
  theme_minimal()
```



```{r}
china <- full_emissions_fao_species %>%
  filter(flag == "CHN")

isscaap_china <- china %>%
  group_by(isscaap_group, isscaap) %>%
  summarise(total_emissions = sum(total_co2_mt, na.rm = TRUE),
            total_catch = sum(country_total_tons_by_species, na.rm = TRUE)) %>%
  mutate(emissions_unit_catch = total_emissions/total_catch)

isscaap_china %>%
  filter(!isscaap %in% c(99999999, 1000000)) %>%
  ggplot(aes(reorder(isscaap_group, emissions_unit_catch), emissions_unit_catch)) +
  geom_col() +
  coord_flip() +
  labs(x ="",
       y = "Emissions/Unit Catch") +
  theme_minimal()
```


```{r}

library(gghighlight)

broadcasting %>%
  filter(flag == "CHN") %>%
  mutate(year = as.numeric(substring(year_month, 1, 4))) %>%
  group_by(year, vessel_class) %>%
  summarise(sum_co2 = sum(emissions_co2_mt, na.rm = TRUE)) %>%
  ggplot(aes(as.factor(year), sum_co2, group = vessel_class)) +
  geom_line() +
  gghighlight(vessel_class == "trawlers") +
  labs(x = "",
       y = "Emissions CO2 (MT)") +
  theme_minimal()


library(treemapify)

broadcasting %>%
  filter(flag == "CHN") %>%
  # Only select fishing vessels (dataset already only selects for fishing activity)
    filter(vessel_class %in% c("fishing","squid_jigger","drifting_longlines",
                               "pole_and_line","other_fishing","trollers","fixed_gear",
                               "pots_and_traps","set_longlines","set_gillnets","trawlers",
                               "dredge_fishing","seiners","purse_seines","tuna_purse_seines",
                               "other_purse_seines","other_seines","driftnets")) %>%
  group_by(vessel_class) %>%
  summarise(sum_co2 = sum(emissions_co2_mt, na.rm = TRUE)) %>%
ggplot(aes(
  area = sum_co2,
  fill = vessel_class,
  label = vessel_class,
)) +
  geom_treemap() +
  geom_treemap_text(colour = "white", place = "centre", grow = TRUE) +
  theme(legend.position = "none") +
  
```

TEST