---
title: "Data Assembly"
author: "Carmen Hoyt"
date: last-modified
format:
  html:
      toc: true
      code-fold: true
editor: visual
execute:
  warning: false
  messages: false
editor_options: 
  chunk_output_type: console
---

# About

This Quarto document hosts the code to assemble the data needed to feed into the Data Pipeline. Please run this document first.

# FAO Catch Data

## Load Packages

```{r}
#| code-summary: Load Packages
library(tidyverse)
library(janitor)
library(here)
```

## Load Data

```{r}
#| code-summary: Load Data
# Read in FAO data
fao_capture_quantity <- read_csv(here("/capstone/seamissions/data/fao_seafood_production/Capture_Quantity.csv"), show_col_types = FALSE) |> clean_names()

fao_country_groups <- read_csv(here("/capstone/seamissions/data/fao_seafood_production/CL_FI_COUNTRY_GROUPS.csv"), show_col_types = FALSE)|> clean_names()

fao_species_groups <- read_csv(here::here("/capstone/seamissions/data/fao_seafood_production/CL_FI_SPECIES_GROUPS.csv"), show_col_types = FALSE)|> clean_names()
```

## Clean Data

```{r}
#| code-summary: Clean Data
# --- Clean Data ----
fao_country_groups_clean <- fao_country_groups |>
  select(un_code, iso3_code, name_en, continent_group_en, official_name_en)

fao_species_groups_clean <- fao_species_groups |>
  select(x3a_code, taxonomic_code, identifier, scientific_name, contains("_en"), major_group)
```

## Join FAO Data

`taxonomic_code` differs
i.e. Argentine anchovy:
121006000206 FAO
1210600206 species_key

used identifier (FAO) = identifier (species_key)

[ISSCAAP groups](https://www.fao.org/fishery/static/ASFIS/ISSCAAP.pdf)

```{r}
#| code-summary: Join Data
# Left join country groups
fao_capture_join <- left_join(fao_capture_quantity, fao_country_groups_clean, by = join_by(country_un_code == un_code)) 

# Left join species groups
fao_capture_join <- left_join(fao_capture_join, fao_species_groups_clean, by = join_by(species_alpha_3_code == x3a_code))

# Define regions
regions <- c(18, 21, 27, 31, 34, 47, 48, 51, 57, 58, 61, 67, 71, 77, 81, 87, 88)

# Clean resulting dataset
fao_catch <- fao_capture_join %>%
# Select desired columns
  select(area_code,
         period,
         iso3_code,
         # This will be the species identifier in the final dataset
         identifier,
         major_group,
         # scientific_name,
         # name_en.y,
         value) %>%
  # Rename columns for consistency
  rename(zone = area_code,
         year = period,
         flag = iso3_code,
         species_identifier = identifier,
         catch = value
         # species = scientific_name,
         # common_name = name_en.y
         ) %>%
  # Filter for >2015 to match emissions data
  filter(year > 2015) %>%
  filter(zone %in% regions) %>%
  mutate(zone = as.integer(zone),
         year = as.integer(year))

fao_cleaned <- fao_catch %>%
  # Filter out mammals(?), plants, and reptiles
  filter(major_group %in% c("PISCES", "CRUSTACEA", "MOLLUSCA", "INVERTEBRATA AQUATICA")) %>%
  group_by(zone, year, flag, species_identifier) %>%
  summarise(fao_catch_tons = sum(catch, na.rm = TRUE), .groups = "drop")

#write_csv(fao_cleaned, file.path("/capstone/seamissions/checkpoint/fao_cleaned_identifier.csv"))
```

