---
title: "FAO SAU Comparison"
format: html
editor: visual
---

## Load Data

```{r}
full_emissions_fao <- read_csv(file.path("/capstone/seamissions/checkpoint/full_emissions_fao.csv"), show_col_types = FALSE)
full_emissions_sau <- read_csv(file.path("/capstone/seamissions/checkpoint/full_emissions_sau.csv"), show_col_types = FALSE)
```

## Clean Data

```{r}
# # Columns to rename
# cols_to_rename <- c(colnames(full_emissions_fao)[str_detect(colnames(full_emissions_fao), "_mt")])
# 
# # Add "fao_" prefix to FAO data
# colnames(full_emissions_fao)[colnames(full_emissions_fao) %in% cols_to_rename] <- paste0("fao_", colnames(full_emissions_fao)[colnames(full_emissions_fao) %in% cols_to_rename])
# 
# # Add "sau_" prefix to SAU data
# colnames(full_emissions_sau)[colnames(full_emissions_sau) %in% cols_to_rename] <- paste0("sau_", colnames(full_emissions_sau)[colnames(full_emissions_sau) %in% cols_to_rename])
```

## Compare Each Pollutant

```{r}
# List pollutants
pollutants <- c("co2", 
                "ch4",
                "n2o",
                "nox",
                "sox",
                "co",
                "vocs",
                "pm2_5",
                "pm10")

# Regional comparison by flag and year
fao_summary <- full_emissions_fao %>%
  group_by(zone, year, flag) %>%
  summarise(fao_total_co2_mt = sum(total_co2_mt, na.rm = TRUE))

sau_summary <- full_emissions_sau %>%
  group_by(zone, year, flag) %>%
  summarise(sau_total_co2_mt = sum(total_co2_mt, na.rm = TRUE))

region_year_flag_comparison_table <- full_join(fao_summary, sau_summary, by = c("zone", "year", "flag")) %>%
  mutate(percent_reported_co2 =round((fao_total_co2_mt/sau_total_co2_mt)*100, 2),
         tonnage_discrepancy_co2 = round(fao_total_co2_mt - sau_total_co2_mt, 2))  %>%
  group_by(zone, year) %>%
  arrange(tonnage_discrepancy_co2, .by_group = TRUE)

write_csv(region_year_flag_comparison_table, file.path("/capstone/seamissions/checkpoint/region_year_flag_comparison_table.csv"))

# Global comparison by flag
fao_summary <- full_emissions_fao %>%
  group_by(flag) %>%
  summarise(fao_total_co2_mt = sum(total_co2_mt, na.rm = TRUE))

sau_summary <- full_emissions_sau %>%
  group_by(flag) %>%
  summarise(sau_total_co2_mt = sum(total_co2_mt, na.rm = TRUE))

global_flag_comparison_table <- full_join(fao_summary, sau_summary, by = "flag") %>%
  mutate(percent_reported_co2 = round((fao_total_co2_mt/sau_total_co2_mt)*100, 2),
         tonnage_discrepancy_co2 = round(fao_total_co2_mt - sau_total_co2_mt, 2)) %>%
  arrange(desc(tonnage_discrepancy_co2), .by_group = TRUE)
  # full_join(to_country_emissions, by = "flag") %>%
  # select(-c(match, vessels, emissions, total_emissions)) %>%
  # full_join(from_country_emissions, by = "flag") %>%
  # select(-c(match, vessels, emissions, total_emissions)) 

write_csv(global_flag_comparison_table, file.path("/capstone/seamissions/checkpoint/global_flag_comparison_table.csv"))

# Regional comparison by flag
fao_summary <- full_emissions_fao %>%
  group_by(zone, flag) %>%
  summarise(fao_total_co2_mt = sum(total_co2_mt, na.rm = TRUE))

sau_summary <- full_emissions_sau %>%
  group_by(zone, flag) %>%
  summarise(sau_total_co2_mt = sum(total_co2_mt, na.rm = TRUE))

zone_flag_comparison_table <- full_join(fao_summary, sau_summary, by = c("zone", "flag")) %>%
  mutate(percent_reported_co2 = round((fao_total_co2_mt/sau_total_co2_mt)*100, 2),
         tonnage_discrepancy_co2 = round(fao_total_co2_mt - sau_total_co2_mt, 2)) %>%
  group_by(zone) %>%
  arrange(tonnage_discrepancy_co2, .by_group = TRUE)

write_csv(zone_flag_comparison_table, file.path("/capstone/seamissions/checkpoint/zone_flag_comparison_table.csv"))

```

# Make Species Key

[The current International Standard Statistical Classification of Aquatic Animals and Plants (ISSCAAP) in use from 2000](https://www.fao.org/fishery/docs/DOCUMENT/cwp/handbook/annex/AnnexS2listISSCAAP2000.pdf)

[Species Codes](https://www.fao.org/fishery/static/ASFIS/ASFIS_References_2024_EN.pdf)

The seven functional groups are: 1. Pisces, 2. Mollusca, 3. Crustacea, 4. Mammalia, 5. Amphibia-ReptileAves, 6. Invertabrata aquatica, 7. Plantae aquaticae

```{r}
fao_species_groups <- read_csv(here::here("/capstone/seamissions/data/fao_seafood_production/CL_FI_SPECIES_GROUPS.csv"), show_col_types = FALSE)|> clean_names()

isscaap_codes <- read_csv(file.path("/capstone/seamissions/data/ISSCAAP_codes/ASFIS_sp_2024.csv"), show_col_types = FALSE) %>% 
  clean_names() %>%
  select(scientific_name, family)

# %>%
#   mutate(family_code = substr(taxonomic_code, 5, 7)) %>%
#   select(-taxonomic_code) %>%
#   distinct()

fao_species_filtered <- fao_species_groups %>%
  select(taxonomic_code, name_en, scientific_name, major_group, yearbook_group_en) %>%
  mutate(functional_group = as.integer(substr(taxonomic_code, 1, 1)),
         genus_species_code = substr(taxonomic_code, 8, 12)) %>%
  mutate(family = case_when(genus_species_code == "XXXXX" ~ scientific_name),
         genus = case_when(str_count(genus_species_code, "X") == 2 ~ sub(" .*", "", scientific_name)))


  mutate(species = case_when(str_count(genus_species_code, "X") == 0 ~ sci))
  
fao_species_filtered <- fao_species_groups %>%
  select(taxonomic_code, name_en, scientific_name, major_group) %>%
  mutate(genus_species_code = substr(taxonomic_code, 8, 12)
         #family_code = substr(taxonomic_code, 5, 7)
         ) %>%
 # left_join(isscaap_codes, by = "scientific_name") %>%
         #species_code = substr(taxonomic_code, 11, 12)) %>%
  mutate(family = ifelse(genus_species_code == "XXXXX", scientific_name, NA),
         genus = case_when(genus_species_code == "XXXXX" ~ NA,
                           TRUE ~ word(scientific_name, 1)),
         genus_species = ifelse(str_count(genus_species_code, "X") == 0, scientific_name, NA)) 

full_emissions_fao_species <- full_emissions_fao %>%
  left_join(fao_species_filtered, by = "taxonomic_code") %>%
  select(-c(taxonomic_code, genus_species_code, genus, scientific_name)) %>% 
  relocate(name_en, major_group, family, genus_species, .after = flag)

write_csv(full_emissions_fao_species, file.path("/capstone/seamissions/checkpoint/full_emissions_fao_species.csv"))


unique(full_emissions_fao_species$major_group)
```

# Including flag analysis information:

```{r}
global_flag_comparison_table_2 <- global_flag_comparison_table %>%
  left_join(to_country_emissions, by = "flag") %>%
  select(-c(match, vessels, emissions, total_emissions))
```


By species?


```{r}
for(i in pollutants) {
  fao_pollutant_col <- colnames(full_emissions_fao)[str_detect(colnames(full_emissions_fao), pollutants[1])]
  sau_pollutant_col <- colnames(full_emissions_sau)[str_detect(colnames(full_emissions_sau), pollutants[1])]
  
  fao_table <- full_emissions_fao %>%
    select(year, zone, flag, species, all_of(fao_pollutant_col)) %>%
    mutate(species = ifelse(is.na(species), "broadcasting, no catch", species))
    #rename(fao_species = species)
  
  sau_table <- full_emissions_sau %>%
    select(year, zone, flag, species, all_of(sau_pollutant_col)) %>%
    mutate(species = ifelse(is.na(species), "broadcasting, no catch", species))
    #rename(sau_species = species)
  
  comparison_table <- full_join(fao_table, sau_table, by = c("zone", "year", "flag", "species"))
  
}
```

