---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}


library(tidyverse)
library(janitor)
library(here)
library(gghighlight)
library(lubridate)
library(ggwordcloud)
library(sf)
library(raster)
library(tmap)
library(treemapify)
library(paletteer)
library(ggstream)
library(scales)
```


```{r}

# ---- Load project data ----

data_directory_base <-  ifelse(Sys.info()["nodename"] == "quebracho" | Sys.info()["nodename"] == "sequoia",
                               "/home/emlab",
                               # Otherwise, set the directory for local machines based on the OS
                               # If using Mac OS, the directory will be automatically set as follows
                               ifelse(Sys.info()["sysname"]=="Darwin",
                                      "/Users/Shared/nextcloud/emLab",
                                      # If using Windows, the directory will be automatically set as follows
                                      ifelse(Sys.info()["sysname"]=="Windows",
                                             "G:/Shared\ drives/nextcloud/emLab",
                                             # If using Linux, will need to manually modify the following directory path based on their user name
                                             # Replace your_username with your local machine user name
                                             "/home/choyt/Nextcloud")))

project_directory <- paste0(data_directory_base, "/projects/current-projects/ocean-ghg-fisheries/data/processed/gfw-emissions/")

# Set file path to data folder
pathway <- "/home/emlab/projects/current-projects/ocean-ghg-fisheries/data/processed/gfw_emissions/"

# Set up import for .csv or .xlsx files
file_names <- list.files(pathway, pattern="*.csv", full.names=TRUE)

# Read in emissions data files
for (i in seq_along(file_names)) {
 if(str_detect(file_names[i], "non")) {
    table_name <- paste("non_broadcasting")
    assign(table_name, read_csv(file_names[i], show_col_types = FALSE) %>%
          clean_names())

  } else if (str_detect(file_names[i], "ais")) {
    table_name <- paste("broadcasting")
    assign(table_name, read_csv(file_names[i], show_col_types = FALSE) %>%
          clean_names())
    
  } else {
    warning("Extra file detected.")
  }
}
```


```{r}
# ---- Clean and prep data for source plots ----

# Add source column and combine datasets
broadcasting <- broadcasting %>% mutate(source = 'broadcasting')
non_broadcasting <- non_broadcasting %>% mutate(source = 'non-broadcasting')
combined_data <- bind_rows(broadcasting, non_broadcasting) %>%
  mutate(year = year(month))

# Summarize total emissions by year and source
source_data <- combined_data %>%
  group_by(year, source) %>%
  summarise(total_emissions = sum(across(starts_with('emissions_')), na.rm = TRUE)) %>%
  ungroup()

# Calculate total emissions per year
total_emissions_per_year <- source_data %>%
  group_by(year) %>%
  summarise(total_emissions_total = sum(total_emissions))

# Merge total emissions back into summary data
source_data <- source_data %>%
  left_join(total_emissions_per_year, by = "year")

# Calculate percentage for each source
source_data <- source_data |>
  filter(year > 2015) |>
  mutate(percentage = total_emissions / total_emissions_total * 100)
```


```{r}
# Create stream plot for emissions type 
ggplot(source_data, aes(x = year, y = total_emissions, fill = source)) +
  geom_stream(type = "ridge") +
  labs(title = "Total Emissions by Year and Source",
       x = "Year",
       y = "Source",
       fill = "Source") +
  theme_minimal()
```


```{r}

# ---- Create the stacked bar chart with percentage annotations ---- 

ggplot(source_data, aes(x = factor(year), y = total_emissions, fill = source)) +
  geom_bar(stat = "identity", position = "stack") +
  
  # Add annotations for proportion
  geom_text(aes(label = sprintf("%.1f%%", percentage)),
            position = position_stack(vjust = 0.5),
            color = "white",
            fontface = "bold",
            size = 5.5) +
  
  scale_fill_manual(values = c('broadcasting' = '#057c91', 'non-broadcasting' = '#ff0000'),
                    labels = c('Broadcasting', 'Non-Broadcasting')) +
  
  scale_y_continuous(labels = label_comma()) +
  
  labs(title = "Total Annual Seafood Emissions by Year and Source",
       x = "Year",
       y = "Total Emissions",
       fill = "Source") +
  
  theme_minimal() +
  
 theme(
    plot.background = element_rect(fill = "#0b2232", color = "#0b2232"),
    panel.background = element_rect(fill = "#0b2232", color = "#0b2232"),
    axis.text = element_text(color = "white", size = 15),
    axis.ticks = element_line(color = "white"),
    axis.line = element_line(color = "white"),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(color = "white"),
    legend.title = element_text(color = "white"),
    plot.title = element_text(color = "white", face = "bold", size = 20),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
  )
```


```{r}
# ---- Create the stacked area chart with percentage annotations ---- 
ggplot(source_data, aes(x = year, y = total_emissions, fill = source)) +
  geom_area(position = "stack") + 
  theme_minimal() +
  
  geom_text(aes(label = ifelse(year %in% c(2016, 2024), NA, sprintf("%.1f%%", percentage))),
            position = position_stack(vjust = 0.5),
            color = "white",
            fontface = "bold",
            size = 5.5) +
  
  scale_fill_manual(values = c('broadcasting' = '#057c91', 'non-broadcasting' = '#ff0000'),
                    labels = c('Broadcasting', 'Non-Broadcasting')) +
  
scale_y_continuous(labels = scales::comma) + #, expand = c(0, 0)
   
  #scale_x_continuous(expand = c(0, 0)) +
  
  labs(title = "Total Annual Seafood Emissions by Year and Source",
       x = "Year",
       y = "Total Emissions",
       fill = "Source") +
  
  theme_minimal() +
  
  theme(
    plot.background = element_rect(fill = "#0b2232", color = "#0b2232"),
    panel.background = element_rect(fill = "#0b2232", color = "#0b2232"),
    axis.text = element_text(color = "white", size = 15),
    axis.ticks = element_line(color = "white"),
    axis.line = element_line(color = "white"),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(color = "white"),
    legend.title = element_text(color = "white"),
    plot.title = element_text(color = "white", face = "bold", size = 20),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )
```


```{r}
# ---- Clean and prep data for source plots ----

# Identify the top 9 vessel classes
top_gear_types <- names(sort(table(combined_data$vessel_class), decreasing = TRUE))[1:9]

# Filter the dataset for only the top 9 vessel classes and summarize emissions
gear_data <- combined_data %>%
  filter(vessel_class %in% top_gear_types) %>%
  group_by(year, vessel_class) %>%  
  summarise(total_emissions = sum(across(starts_with('emissions_')), na.rm = TRUE)) %>% 
  ungroup()

```


```{r}
# Define large seamissions color palette
seamissions_large_palette <- c(
  "#00D9FF","#057C91", "#9058C6", "#F781BF", "#FF0000", 
  "#FB8C22", "#FFFF33", "#4EAF4A", "#DBEBBE", "#A8825E")
```

```{r}
# --- Create proportional stream area chart for emissions by vessel class ----
ggplot(gear_data, aes(x = year, y = total_emissions, fill = vessel_class)) +
  geom_stream(type = "proportional") +
  scale_fill_manual(values = seamissions_large_palette) +
  theme_minimal() +
  labs(
    title = "Stream Graph of Vessel Emissions Over Time",
    x = "Year",
    y = "Total Emissions",
    fill = "Vessel Class"
  ) + 
geom_text(aes(x = 2020.0, y = .75, 
                label = "Drifting Longlines"), 
            hjust = 0, vjust = 1.5, size = 5, fontface = "bold", color = "black") 
```

```{r}
# --- Create proportional stream area chart for emissions by vessel class ----
ggplot(gear_data, aes(x = year, y = total_emissions, fill = vessel_class)) +
  geom_stream(type = "ridge") +
  scale_fill_manual(values = seamissions_large_palette) +
  theme_minimal() +
  labs(
    title = "Stream Graph of Vessel Emissions Over Time",
    x = "Year",
    y = "Total Emissions",
    fill = "Vessel Class"
  )
```


```{r}


# group by year and gear type, sum total emissions

# Create the stacked area plot
ggplot(summary_data , aes(x = year, y = count, fill = c_name)) +
    geom_stream(type = "ridge", alpha = 0.7) +  # Stacked area chart
    scale_x_continuous(breaks = seq(min(ca_salmon_species_year$y_end), max(ca_salmon_species_year$y_end), by = 5)) + # Adjust X-axis breaks
    labs(title = "CA Salmon Population Over Time",
         x = "Year",
         y = "Count",
         fill = "Species") +
    theme_minimal()
```


