---
title: "Spring Approach"
date: last-modified
format:
  html:
      toc: true
      code-fold: true
editor: visual
execute:
  warning: false
  messages: false
editor_options: 
  chunk_output_type: console
---

# About

This repository hosts the code for the open-source data processing pipeline.

## Load packages

```{r}
#| code-summary: Expand code
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(sf)
library(dplyr)
```

## Load data

```{r}
#| code-summary: Load emissions data

# Turn off scientific notation
options(scipen=999)

# Set file path to data folder workbench-2
pathway <- "/capstone/seamissions/data/meds_capstone_project"

# Set up import for .csv or .xlsx files
file_names <- list.files(pathway, pattern="*.csv", full.names=TRUE)

# Read in emissions data files
for (i in seq_along(file_names)) {
 if(str_detect(file_names[i], "non")) {
    table_name <- paste("non_broadcasting")
    assign(table_name, read_csv(file_names[i], show_col_types = FALSE) %>%
          clean_names())

  } else if (str_detect(file_names[i], "ais")) {
    table_name <- paste("broadcasting")
    assign(table_name, read_csv(file_names[i], show_col_types = FALSE) %>%
          clean_names())
    
  } else {
    warning("Extra file detected.")
  }
}
```

# Merge Emissions Datasets

## Clean Data

```{r}
#| code-summary: Clean Data
# Create `year_month` column
broadcasting <- broadcasting %>%
  mutate(date = lubridate::ymd(month)) %>%
  mutate(year_month = format(date, '%Y-%m'))
  
# Create `year_month` column 
non_broadcasting <- non_broadcasting %>%
  mutate(date = lubridate::ymd(month)) %>%
  mutate(year_month = format(date, '%Y-%m')) %>%
  mutate(flag = "DARK")

colnames(non_broadcasting)[str_detect(colnames(non_broadcasting), "non_broadcasting")] <- str_remove(colnames(non_broadcasting)[str_detect(colnames(non_broadcasting), "non_broadcasting")], "_non_broadcasting") 

if (unique(colnames(non_broadcasting)[str_detect(colnames(non_broadcasting), "emissions")] == colnames(broadcasting)[str_detect(colnames(broadcasting), "emissions")]) != TRUE) {
  warning("Column names don't match.")
}
```

## Join Data

```{r}
#| code-summary: Join Broadcasting and Non-Broadcasting Datasets
# Combine dataframes
emissions <- bind_rows(broadcasting, non_broadcasting)

if(nrow(broadcasting) + nrow(non_broadcasting) != nrow(emissions)) {
  warning("Number of rows doesn't add up, emissions data lost.")
}
```

## Check for Discrepancies

```{r}
#| code-summary: Expand code

# List pollutants
pollutants <- c("co2", 
                "ch4",
                "n2o",
                "nox",
                "sox",
                "co",
                "vocs",
                "pm2_5",
                "pm10")

# Check for discrepancies
for (i in seq_along(pollutants)) {

  em_col <- paste0("emissions_", pollutants[1], "_mt")
  
  # Total emissions before factoring
  em_before <- sum(broadcasting[[em_col]], na.rm = TRUE) + sum(non_broadcasting[[em_col]], na.rm = TRUE)
  
  # Total emissions after factoring
  em_after <- sum(emissions[[em_col]], na.rm = TRUE)
  
  # Difference in emissions
  diff <- em_after - em_before
  
  # Trigger error warning for lost emissions over 0.1%
  if (diff > 0) {
    warning(paste0("Non-zero difference returned for ", {pollutants[i]}, ". Some emissions may be lost."))
  }  
}
```

### Checkpoint

```{r}
#| code-summary: Expand code

# -------- Create "checkpoint" folder if needed --------

# Save emissions dataset to workbench-2
#write_csv(emissions, file.path("/capstone/seamissions/checkpoint/emissions.csv"))

# Read in emissions dataset
#emissions <- read_csv(file.path("/capstone/seamissions/checkpoint/emissions.csv"), show_col_types = FALSE)
```

# Spatial Join FAO Regions and Emissions

## Import and clean data

```{r}
#| code-summary: Expand code

# -------- set up projections --------
# equal earth 8857
#my_crs <- st_crs("+proj=eqearth +datum=WGS84 +units=m +no_defs")

# OR mollweide projection 54009 (but not recognized)
#mollweide_proj <- "+proj=moll +lon_0=0 +datum=WGS84 +units=m +no_defs"
#emissions_sf <- st_set_crs(emissions_sf, mollweide_proj) # transform?

# -------- EMISSIONS --------
# Filter for desired variables
emissions_filtered <- emissions %>%
  # Create year column
  mutate(year = as.integer(substr(year_month, 1, 4))) %>%
  # Group by pixel, year, and flag
  group_by(lat_bin, lon_bin, year, flag) %>% # vessel_class
  # Sum co2 (ADD OTHER POLLUTANTS HERE)
  summarise(co2_mt = sum(emissions_co2_mt, na.rm = TRUE),
            ch4_mt = sum(emissions_ch4_mt, na.rm = TRUE),
            n2o_mt = sum(emissions_n2o_mt, na.rm = TRUE),
            nox_mt = sum(emissions_nox_mt, na.rm = TRUE),
            sox_mt = sum(emissions_sox_mt, na.rm = TRUE),
            co_mt = sum(emissions_co_mt, na.rm = TRUE),
            vocs_mt = sum(emissions_vocs_mt, na.rm = TRUE),
            pm2_5_mt = sum(emissions_pm2_5_mt, na.rm = TRUE),
            pm10_mt = sum(emissions_pm10_mt, na.rm = TRUE))

# Convert lat/long to point geometry (degrees)
emissions_sf <- emissions_filtered %>%
  # add lat and lon bin to preserve for merge 
  dplyr::mutate(lat = lat_bin, lon = lon_bin) %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326) # import as WGS (unit = degrees)

# Create grid throughout extent of emissions_sf from point geometry
emissions_grid <- emissions_sf %>%
  st_make_grid(cellsize = c(1,1),
               what = "polygons") %>%
  st_sf() %>%
  st_make_valid() %>%
  mutate(grid_id = row_number())
  
# Spatially join emissions data to the grid
emissions_grid_sf <- st_join(emissions_grid, emissions_sf, left = FALSE) %>%
  # Transform to Equal Earth projection
  st_transform(6933)
```

### Checkpoint

```{r}
#| code-summary: Checkpoint
#| 
# Save emissions_grid_sf to workbench-2
#st_write(emissions_grid_sf, file.path("/capstone/seamissions/checkpoint/emissions_grid_sf.gpkg"), delete_dsn = TRUE)

# Read in emissions_grid_sf from workbench-2
#emissions_grid_sf <- st_read(file.path("/capstone/seamissions/checkpoint/emissions_grid_sf.gpkg"))

# Save cleaned fao_catch data
#write_csv(fao_catch, file.path("/capstone/seamissions/checkpoint/fao_catch.csv"))

# Read in fao catch data
#fao_catch <- read_csv(file.path("/capstone/seamissions/checkpoint/fao_catch.csv"), show_col_types = FALSE)
```

## Run intersection

```{r}
#| code-summary: Intersection

# -------- FAO REGIONS --------
# Import regions data (set same crs) from workbench-2
fao_regions <- st_read(file.path("/capstone/seamissions/data/fao_region_shapefile")) %>%
  # Transform to same crs as grid
  st_transform(st_crs(emissions_grid_sf)) %>%
  # Fix geometries
  st_make_valid()

# Confirm crs match
if (st_crs(emissions_grid_sf) != st_crs(fao_regions)){
  warning("CRS don't match.")
}

# Find which grid cells intersect with the FAO regions
emissions_zones <- st_intersection(emissions_grid_sf, fao_regions) 

emissions_zones$area <- as.numeric(st_area(emissions_zones))
```

### Checkpoint

```{r}
#| code-summary: Checkpoint 
# Save emissions_zones to workbench-2
#st_write(emissions_zones, file.path("/capstone/seamissions/checkpoint/emissions_zones.gpkg"), delete_dsn = TRUE)

# Read in emissions_zones from workbench-2
#emissions_zones <- st_read(file.path("/capstone/seamissions/checkpoint/emissions_zones.gpkg"))
```

## Partition emissions by proportional area

```{r}
#| code-summary: Partition emissions 
# Inspect geometry types in emissions_zones
geom_types <- unique(st_geometry_type(emissions_zones))

# Specify desired geometry types POLYGON or MULTIPOLYGON 
valid_types <- c("POLYGON", "MULTIPOLYGON")

# Identify unexpected types
invalid_types <- setdiff(geom_types, valid_types) # contains POINT (?)

# Warning if geometry types besides POLYGON or MULTIPOLYGON found
if(length(invalid_types > 0)) {
  warning("Additional geometry types detected.")
}

#table(st_geometry_type(emissions_zones))

# Remove other geometry types (filter out POINT)
emissions_zones_filtered <- emissions_zones %>%
  filter(st_geometry_type(.) %in% valid_types) # in valid_types, c("POLYGON", "MULTIPOLYGON")

# Break MULTIPOLYGONS down into POLYGONS
emissions_zones_exploded <- st_cast(emissions_zones_filtered, "MULTIPOLYGON") %>% 
  st_cast("POLYGON")

#table(st_geometry_type(emissions_zones_exploded))

# Generate areas by grid_id for sub polygons
emissions_zones_summary_1 <- emissions_zones_exploded %>%
  group_by(grid_id, geom) %>%
  summarise(
    number_areas = n_distinct(area),
    .groups = "drop") %>% # keep?
  mutate(area_summary = as.numeric(st_area(geom))) %>%
  ungroup()

# Add up sub polygon areas for overall grid_id area
emissions_zones_summary_2 <- emissions_zones_summary_1 %>%
  group_by(grid_id) %>%
  summarise(
    unique_areas = paste(unique(area_summary), collapse = ", "),
    number_areas = sum(number_areas),
    total_unique_area = sum(area_summary, na.rm = TRUE))

# Made a key of grid_id and overall grid_id area
grid_id_key <- emissions_zones_summary_2 %>%
  select(grid_id, total_unique_area) %>%
  st_drop_geometry()

# Join key with emissions_zones
emissions_zones_joined <- left_join(emissions_zones, grid_id_key)

# build in warning for matching rows? ids?
if(nrow(emissions_zones_joined) != nrow(emissions_zones)) {
  warning("Incorrect join: too many rows.")
}

# Partition out emissions by area proportion
emissions_partitioned <- emissions_zones_joined %>%
  # Calculate proportion
  mutate(prop = area/total_unique_area) %>%
  # Partition emissions
  mutate(prop_co2_mt = co2_mt * prop,
         prop_ch4_mt = ch4_mt * prop,
         prop_n2o_mt = n2o_mt * prop,
         prop_nox_mt = nox_mt * prop,
         prop_sox_mt = sox_mt * prop,
         prop_co_mt = co_mt * prop,
         prop_vocs_mt = vocs_mt * prop,
         prop_pm2_5_mt = pm2_5_mt * prop,
         prop_pm10_mt = pm10_mt * prop)

# Check for discrepancies
for (i in seq_along(pollutants)) {
  
  # Assign column names
  sf_col <- paste0(pollutants[i], "_mt")
  prop_col <- paste0("prop_", pollutants[i], "_mt")
  
  # Total emissions before factoring
  em_before <- sum(emissions_grid_sf[[sf_col]], na.rm = TRUE)
  
  # Total emissions after factoring
  em_after <- sum(emissions_partitioned[[prop_col]], na.rm = TRUE)
  
  # Difference in emissions
  diff <- em_after - em_before
  
  # Percent error
  error <- diff/em_before
  
  #print(error)
  
  # Error warning for lost emissions over 5% (DECISION POINT)
  if (error > 0.05) {
  warning(paste0("Error over 5% returned for ", {pollutants[i]}, " emissions partitioning. Some emissions may be lost."))
  }
}
```

### Checkpoint

```{r}
#| code-summary: Checkpoint 
# Save emissions_partitioned to workbench-2
#st_write(emissions_partitioned, file.path("/capstone/seamissions/checkpoint/emissions_partitioned.gpkg"), delete_dsn = TRUE)

# Read in emissions_zones from workbench-2
#emissions_partitioned <- st_read(file.path("/capstone/seamissions/checkpoint/emissions_partitioned.gpkg"))
```

