---
title: "Visualizations"
author: "Carmen Hoyt"
date: last-modified
format:
  html:
      toc: true
      code-fold: true
editor: visual
execute:
  warning: false
  messages: false
editor_options: 
  chunk_output_type: console
---

# Load Packages and Data

```{r}
#| code-summary: Load Data

library(tidyverse)

full_emissions_fao <- read_csv(file.path("/capstone/seamissions/checkpoint/full_emissions_fao.csv"), show_col_types = FALSE)

full_emissions_fao_species <- read_csv(file.path("/capstone/seamissions/checkpoint/full_emissions_fao_species.csv"))
```

# Trends in global emissions by FAO region

```{r}
#| code-summary: Emissions by Region
#| fig-asp: 0.6

# Plot all Regions
full_emissions_fao %>%
  group_by(zone, year) %>%
  summarise(total_emissions_co2 = sum(total_co2_mt, na.rm = TRUE)) %>%
  ggplot(aes(year, total_emissions_co2, color = as.factor(zone))) +
  geom_line() +
  labs(x = "",
       y = "Emissions CO2 (mt)",
       title = "Emissions CO2 by Zone over Time",
       color = "Zone") +
  scale_y_continuous(labels = scales::comma) +
  gghighlight::gghighlight(zone %in% c(27, 61)) +
  theme_minimal()

# Facet by Region
full_emissions_fao %>%
  group_by(zone, year) %>%
  summarise(total_emissions_co2 = sum(total_co2_mt, na.rm = TRUE)) %>%
  ggplot(aes(year, total_emissions_co2, group = as.factor(zone))) +
  geom_line() +
  scale_x_continuous(breaks = seq(2016, 2024, by = 4)) +
  scale_y_continuous(labels = scales::comma) +
  # Facet by Region
  facet_wrap(~zone, scales = "free_y") +
  labs(x = "",
       y = "Emissions (mt) CO2",
       title = "Trends in Global Emissions by FAO Region") +
  theme_minimal()
```

# Trends in emissions-per-unit-catch by ISSCAAP species group

```{r}
#| code-summary: ISSCAAP Time
full_emissions_fao_species %>%
  filter(year<=2022) %>%
  filter(!isscaap_group == "no_fao_species_catch_data") %>%
  group_by(isscaap_group, isscaap, year) %>%
  summarise(total_emissions_co2 = sum(total_co2_mt, na.rm = TRUE),
            total_catch = sum(country_total_tons_by_species, na.rm = TRUE)) %>%
  mutate(emissions_unit_catch = total_emissions_co2/total_catch) %>%
  ggplot(aes(year, emissions_unit_catch, group = isscaap_group)) +
  geom_line() +
  scale_x_continuous(breaks = seq(2016, 2022, by = 3)) +
  facet_wrap(~isscaap_group, labeller = label_wrap_gen(width = 20), scales = "free_y") +
  labs(x = "",
       y = "Emissions CO2 per Unit Catch") +
  theme_minimal()
```

### ISSCAAP Group Boxplot

```{r}
#| code-summary: ISSCAAP Emissions-Catch
# Summarise FAO by isscaap group
fao_summary <- full_emissions_fao_species %>%
  group_by(flag, isscaap_group) %>%
  summarise(fao_total_co2_mt = sum(total_co2_mt, na.rm = TRUE),
            fao_total_catch = sum(country_total_tons_by_species, na.rm = TRUE)) %>%
  mutate(fao_emissions_unit_catch = ifelse(fao_total_catch == 0, 0, fao_total_co2_mt/fao_total_catch)) %>%
  select(-c(fao_total_co2_mt, fao_total_catch))

# Plot
fao_summary %>%
  # Select top groups(?)
  filter(isscaap_group %in% c("Corals", "Scallops, pectens", "Krill, planktonic crustaceans", "Mussels", "Salmons, trouts, smelts", "Cods, hakes, haddocks", "Miscellaneous marine crustaceans", "King crabs, squat-lobsters", "Sea-squirts and other tunicates", "Sharks, rays, chimeras", "Clams, cockles, arkshells")) %>%
  #filter(isscaap_group %in% c("Carps, barbels, and other cyprinids", "Salmons, trouts, smelts", "King crabs, squat-lobsters", "Sturgeons, paddlefishes", "Krill, planktonic crustaceans", "Cods, hakes, haddocks", "Scallops, pectens", "Corals", "Sea-squirts and other tunicates", "Mussels", "Sponges", "Clams, cockles, arkshells", "Oysters")) %>%
 ggplot(aes(reorder(isscaap_group, fao_emissions_unit_catch), fao_emissions_unit_catch)) +
  geom_boxplot() +
  coord_flip() +
  scale_y_continuous(limits = c(0, 25)) +
  labs(x = "",
       y = "Emissions CO2/Unit Catch",
       title = "Emissions CO2 per Unit Catch by ISSCAAP Group") +
  theme_minimal()
```

# Trends in emissions-per-unit-catch by FAO region 

```{r}
#| code-summary: Region Emissions-Catch

# Facet by region
full_emissions_fao %>%
  filter(year <= 2022) %>%
  group_by(zone, year) %>%
  summarise(total_emissions_co2 = sum(total_co2_mt, na.rm = TRUE),
            total_catch = sum(country_total_tons_by_species, na.rm = TRUE)) %>%
  mutate(emissions_unit_catch = total_emissions_co2/total_catch) %>%
  ggplot(aes(year, emissions_unit_catch, group = as.factor(zone))) +
  geom_line() +
  scale_x_continuous(breaks = seq(2016, 2024, by = 4)) +
  #scale_y_continuous(labels = scales::comma) +
  facet_wrap(~zone, scales = "free_y") +
  labs(x = "",
       y = "Emissions CO2 per Unit Catch",
       title = "Trends in Global Emissions per Unit Catch by FAO Region") +
  theme_minimal()

full_emissions_fao %>%
  filter(year <= 2022) %>%
  group_by(zone, year) %>%
  summarise(total_emissions_co2 = sum(total_co2_mt, na.rm = TRUE),
            total_catch = sum(country_total_tons_by_species, na.rm = TRUE)) %>%
  mutate(emissions_unit_catch = total_emissions_co2/total_catch) %>%
  filter(!zone == 18) %>%
  ggplot(aes(year, emissions_unit_catch, group = as.factor(zone), color = as.factor(zone))) +
  geom_line() +
  scale_x_continuous(breaks = seq(2016, 2024, by = 4)) +
  labs(x = "",
       y = "Emissions CO2 per Unit Catch",
       title = "Trends in Global Emissions per Unit Catch by FAO Region",
       color = "Zone") +
  gghighlight::gghighlight(as.factor(zone) %in% c(58, 88)) +
  theme_minimal()
```

### Fishery

```{r}
# code-summary: Fishery
# Summarise FAO data
fao_summary <- full_emissions_fao_species %>%
  group_by(zone, flag, isscaap_group) %>%
  summarise(fao_total_co2_mt = sum(total_co2_mt, na.rm = TRUE),
            fao_total_catch = sum(country_total_tons_by_species, na.rm = TRUE)) %>%
  mutate(fao_emissions_unit_catch = ifelse(fao_total_catch == 0, 0, fao_total_co2_mt/fao_total_catch)) %>%
  select(-c(fao_total_co2_mt, fao_total_catch))

fao_summary %>%
  filter(!isscaap_group == "no_fao_species_catch_data") %>%
ggplot(aes(as.factor(zone), fao_emissions_unit_catch, group = as.factor(zone))) +
  geom_boxplot() +
  scale_y_continuous(limits = c(0,100)) +
  labs(x = "FAO Zone",
       y = "Emissions CO2/Unit Catch",
       title = "Emissions CO2 per Unit Catch by Zone") +
  theme_minimal()
```

Examine which fisheries are outlier

